---
new_page_extension: md
auto_deploy: false
admin_path: fadmin
webhook_url: 
sections:
- type: directory
  path: ''
  label: Files
  create: all
  match: "**/*"
- type: directory
  path: content/posts
  label: Posts
  create: all
  match: "**/*"
  exclude: _index.md
- type: heading
  label: English Site
- type: document
  path: data/en/author.yaml
  label: Site Author
- type: document
  path: data/en/site.yaml
  label: Site Settings
- type: directory
  path: data/en/sections
  label: Site Sections
  create: all
  match: "**/*"
- type: heading
  label: Site Settings
- type: document
  path: config.yml
  label: Config
- type: document
  path: README.md
  label: README.md
upload_dir: assets/images
public_path: "/assets/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.96.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
